/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StateComparisonRouteImport } from './routes/state-comparison'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as IndiaMapRouteImport } from './routes/india-map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CioRouteImport } from './routes/cio'
import { Route as IndexRouteImport } from './routes/index'

const StateComparisonRoute = StateComparisonRouteImport.update({
  id: '/state-comparison',
  path: '/state-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaMapRoute = IndiaMapRouteImport.update({
  id: '/india-map',
  path: '/india-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CioRoute = CioRouteImport.update({
  id: '/cio',
  path: '/cio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cio': typeof CioRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/india-map': typeof IndiaMapRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/login': typeof LoginRoute
  '/state-comparison': typeof StateComparisonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cio': typeof CioRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/india-map': typeof IndiaMapRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/login': typeof LoginRoute
  '/state-comparison': typeof StateComparisonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cio': typeof CioRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/india-map': typeof IndiaMapRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/login': typeof LoginRoute
  '/state-comparison': typeof StateComparisonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cio'
    | '/dashboard'
    | '/home'
    | '/india-map'
    | '/knowledge-graph'
    | '/login'
    | '/state-comparison'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cio'
    | '/dashboard'
    | '/home'
    | '/india-map'
    | '/knowledge-graph'
    | '/login'
    | '/state-comparison'
  id:
    | '__root__'
    | '/'
    | '/cio'
    | '/dashboard'
    | '/home'
    | '/india-map'
    | '/knowledge-graph'
    | '/login'
    | '/state-comparison'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CioRoute: typeof CioRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  IndiaMapRoute: typeof IndiaMapRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  LoginRoute: typeof LoginRoute
  StateComparisonRoute: typeof StateComparisonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/state-comparison': {
      id: '/state-comparison'
      path: '/state-comparison'
      fullPath: '/state-comparison'
      preLoaderRoute: typeof StateComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india-map': {
      id: '/india-map'
      path: '/india-map'
      fullPath: '/india-map'
      preLoaderRoute: typeof IndiaMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cio': {
      id: '/cio'
      path: '/cio'
      fullPath: '/cio'
      preLoaderRoute: typeof CioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CioRoute: CioRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  IndiaMapRoute: IndiaMapRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  LoginRoute: LoginRoute,
  StateComparisonRoute: StateComparisonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
